import {
  MenuIcon,
  ShoppingBagIcon,
  ArrowNarrowRightIcon,
  ArrowNarrowLeftIcon,
} from "@heroicons/react/outline";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Main from "../components/Main";

export default function Home() {
  return (
    <div className="flex w-full h-screen">
      <Head>
        <title>Design to Develop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          background: `url(https://res.cloudinary.com/dssvrf9oz/image/upload/v1622697328/Screenshot_2021-06-03_095340_lauqh3.png)`,
        }}
        className="w-1/2 !bg-cover px-10"
      >
        <Header />
        <Main />
      </div>

      <div className="relative h-screen w-1/2">
        <Image
          className="z-[-10]"
          src="https://i.pinimg.com/originals/e8/e6/61/e8e6617f6c10eedb34737462e05d55a4.jpg"
          layout="fill"
        />
        <MenuIcon className="h-10 w-10 !right-10 ml-auto m-6 rounded-lg bg-white p-1" />
        <div className="absolute bottom-0 bg-white bg-opacity-40 backdrop-filter w-full h-48 flex justify-between items-center">
          <div className="ml-10">
            <div className="flex items-center ">
              <h2 className="text-lg font-semibold">Fluffy T-shirt</h2>
              <ShoppingBagIcon className="h-6 w-6" />
            </div>
            <p className="text-lg font-semibold">$120.90</p>
          </div>
          <div className="flex mr-10">
            <div className="rounded-full p-5 ring-2 ring-white">
              <ArrowNarrowLeftIcon className="h-9 w-9 rounded-full ring-2 ring-white text-white" />
            </div>
            <div className="rounded-full p-5 ring-2 ring-primary_purple ml-5 bg-primary_purple">
              <ArrowNarrowRightIcon className="h-9 w-9 rounded-full ring-2 ring-white text-white bg-primary_purple" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
